# Sostituisci "app" con un nome unico globale se questo è già preso.
app = "nexus-social-peterlini"
primary_region = "fra"

[build]

[env]
  DB_PATH = "/data/nexus.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "nexus_data"
  destination = "/data"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
